language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - PHPCS=0

services:
  - elasticsearch

matrix:
  include:
    - php: 5.6
      env: PHPCS=1

before_script:
  - sleep 7 # Work around elasticsearch startup time.
  - phpenv rehash

install:
  - composer self-update
  - composer install --dev

script:
  - phpunit
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi"

notifications:
  email: false
