language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - elasticsearch

before_script:
  - sleep 7 # Work around elasticsearch startup time.
  - phpenv rehash

install:
  - composer self-update
  - composer install --dev

script:
  - phpunit
  - vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests

notifications:
  email: false
